[package]
name = "cuvslam"
version = "0.1.0"
edition = "2021"

[dependencies]
cuvslam-lib = { path = "../cuvslam-lib" }
realsense-rust = "*"
rerun = "0.22.1"

[[bin]]
name = "realsense"
path = "src/bin/realsense.rs"
